#!/bin/bash
#
# Copyright 2019 Gaël PORTAY
#
# SPDX-License-Identifier: GPL-3-or-later
#

set -e

if [[ $# -eq 0 ]]
then
	cat <<EOF >&2
Usage: ${0##*/} SIGNAL [NAME]
EOF
	exit 1
fi

case "${3:-$button}" in
1|on)
	on="on"
	;;
3|off)
	on="off"
	;;
esac

if [[ "${on,,}" =~ ^(on|1|true)$ ]]
then
	on="on"
	color="#00ff00"

	if ! output="$(killall "-$1" "${2:-$name}" 2>&1)"
	then
		printf '{"full_text":"%s", "on":"%s"}\n' "${output//\"/}" "$on"
		exit 33
	fi
else
	on="off"
	color="#ff0000"
fi

printf '{"full_text":"%s", "color":"%s", "on":"%s"}\n' "${name}: $on" "$color" "$on"
